embed_assets: on
javascript_compressor: closure # (yui, closure)

javascripts:
  common:
    - public/javascripts/lib/modernizr.js
    - public/javascripts/lib/webfonts.js
    - public/javascripts/jquery/jquery.js
    - public/javascripts/jquery/jquery.blockUI.js
    - public/javascripts/jquery/jquery.formalize.js
    - public/javascripts/lib/underscore.js
    - public/javascripts/lib/rails.js
    - public/javascripts/application.js
  admin:
stylesheets:
  common:
    - public/stylesheets/application.css
  admin:
